eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: service-zuul
  http:
      # 多文件上传配置
      multipart:
        max-file-size: 5Mb      # Max file size，默认1M
        max-request-size: 50Mb   # Max request size，默认10M

redis:
  host: 127.0.0.1
  port: 6379
  password: jinwei
  # 客户端超时时间单位是毫秒 默认是2000
  timeout: 20000
  #最大空闲数  
  maxIdle: 300
  #控制一个pool可分配多少个jedis实例,用来替换上面的maxActive,如果是jedis 2.4以后用该属性  
  maxTotal: 1000  
  #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。  
  maxWaitMillis: 1000  
  #连接的最小空闲时间 默认1800000毫秒(30分钟)  
  minEvictableIdleTimeMillis: 300000  
  #每次释放连接的最大数目,默认3  
  numTestsPerEvictionRun: 1024  
  #逐出扫描的时间间隔(毫秒) 如果为负数,则不运行逐出线程, 默认-1  
  timeBetweenEvictionRunsMillis: 30000  
  #是否在从池中取出连接前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个  
  testOnBorrow: true
  #在空闲时检查有效性, 默认false  
  testWhileIdle: true  

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: service-ribbon
    api-b:
      path: /api-b/**
      serviceId: service-feign
    api-user:
      path: /api-user/**
      serviceId: service-user
    api-file:
      path: /api-file/**
      serviceId: service-file